[package]
distribution = "2201.9.3"
org = "ballerinax"
name = "ai.azure.index"
version = "1.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["AI/Search", "Azure", "Cost/Paid", "Search Index", "Azure AI Search", "Vendor/Microsoft"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-ai.azure.index"

[build-options]
observabilityIncluded = true